//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2013.RefugeesUnited.Model
{
	using System;
	using System.Data.Entity;
	using System.Data.Entity.Infrastructure;
	using Tam.Lib.Model;

	public partial class ModelContainer : DbContext, IDbContext
	{
		public ModelContainer()
			: base("name=ModelContainer")
	    {
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			throw new UnintentionalCodeFirstException();
		}

		public DbSet<Device> Devices { get; set; }
		public DbSet<User> Users { get; set; }
		public DbSet<Session> Sessions { get; set; }
	}
}
