//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2013.RefugeesUnited.Model
{
	using System;
    using System.Collections.Generic;
    using Tam.Lib.Model;

	public partial class Session : IEntity
	{
		public long Id { get; private set; }
		public string UssdId { get; set; }
		public System.DateTime StartTimestamp { get; set; }
		public System.DateTime ActivityTimestamp { get; set; }
		public SessionState State { get; set; }
		public string StateJson { get; set; }
		public virtual User User { get; set; }
	}
}
