//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2013.RefugeesUnited.Model
{
	using System;
    using System.Collections.Generic;
    using Tam.Lib.Model;

	public partial class User : IEntity
	{
		public long Id { get; private set; }
		public string ApiId { get; set; }
		public virtual Device Device { get; set; }
		public virtual Session Session { get; set; }
	}
}
