//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2013.RefugeesUnited.Data
{
  using Tam.Lib.Data;
  using RS2013.RefugeesUnited.Model;
  
  public partial interface IUserRepository : IRepository<User>
  {
  }
}
